trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Build the application"

- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: DEV
    strategy:
      runOnce:
        deploy:     
          steps:
          - bash: echo "Deploy on Dev Env"

- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
      runOnce:
        deploy:     
          steps:
          - bash: echo "Deploy on QA Env"
          